### ISSUE TITLE
Sentry gun/engineer outline colours do not change with colour override

### ISSUE THREAD

**Issue by mitchcl** [dalegaard/CastingEssentials#2]

**Comment by dalegaard** [comment]
I'll need some more info to go on for this, preferably screenshots, a demo, and how to reproduce the problem.

**Comment by Wiethoofd** [comment]
Also the commands are `ce_outlines_players_override_blue` & `ce_projectileoutlines_color_blu` for players and outlines respectively, wouldn't expect those to affect buldings.

**Comment by mitchcl** [comment]
> I'll need some more info to go on for this, preferably screenshots, a demo, and how to reproduce the problem.

The command `ce_outlines_players_override_blue` & `ce_outlines_players_override_red` do not override player utilities such as the Engineers dispenser, Sentry gun etc. 

I would assume this should be overridable with the command as it would look weird having them in the default colours.

![image](https://user-images.githubusercontent.com/21251983/114016767-87805c80-98ae-11eb-9aa9-1d2feb11a554.png)

**Comment by dalegaard** [comment]
Would this be new override commands, or should the existing two commands be extended to apply to buildings as well? What is you take on that, @Wiethoofd ?

**Comment by Wiethoofd** [comment]
I would make them separate from players & outlines: `ce_outlines_buildings_override_blue`, and perhaps for consistency also change the outlines one to match the same naming scheme.
