### ISSUE TITLE
Crashes the server on current TF2 ver

### ISSUE THREAD

**Issue by agrastiOs** [dalegaard/CastingEssentials#3]
Hi, 

This is currently unusable. Crashes the server with 
![paveikslas](https://user-images.githubusercontent.com/15906773/147880098-4fe1c93a-9e2a-4703-a2bc-29df0d0dcbe9.png)

**Comment by dalegaard** [comment]
CastingEssentials is a client plugin, not a server plugin.

**Comment by agrastiOs** [comment]
Yeah... No idea what happened today, that I even thought of this issue. Sorry for this essentially being a shitpost issue.
